const tickets = [
  // 🎵 Concerts
  {
    eventName: "Arijit Singh Live in Mumbai",
    eventDate: new Date("2025-12-15"),
    pricePerTicket: 2500,
    ticketsAvailable: 120,
    owner: "68ff509c77bb306c3224e66e",
    location: "Jio World Garden, Mumbai",
    eventCategory: "Concert",
    description: "Experience the magic of Arijit Singh's soulful voice live in concert.",
  },
  {
    eventName: "Coldplay – Music of the Spheres Tour",
    eventDate: new Date("2025-11-05"),
    pricePerTicket: 4500,
    ticketsAvailable: 250,
    owner: "68ff509c77bb306c3224e66e",
    location: "Bangalore Palace Grounds, Bengaluru",
    eventCategory: "Concert",
    description: "Coldplay returns to India with a spectacular light show and hit songs.",
  },

  // ⚽ Sports
  {
    eventName: "India vs Australia – ODI Match",
    eventDate: new Date("2025-12-02"),
    pricePerTicket: 1800,
    ticketsAvailable: 500,
    owner: "68ff509c77bb306c3224e66e",
    location: "Eden Gardens, Kolkata",
    eventCategory: "Sports",
    description: "Catch the thrilling clash between India and Australia live!",
  },
  {
    eventName: "ISL Semi-Final: Mumbai City FC vs Kerala Blasters",
    eventDate: new Date("2025-11-28"),
    pricePerTicket: 1200,
    ticketsAvailable: 350,
    owner: "68ff509c77bb306c3224e66e",
    location: "Mumbai Football Arena, Mumbai",
    eventCategory: "Sports",
    description: "A high-voltage ISL semi-final between two crowd favourites.",
  },

  // 🎭 Theatre
  {
    eventName: "The Phantom of the Opera",
    eventDate: new Date("2025-11-20"),
    pricePerTicket: 2200,
    ticketsAvailable: 100,
    owner: "68ff509c77bb306c3224e66e",
    location: "NCPA, Mumbai",
    eventCategory: "Theatre",
    description: "A timeless classic musical brought to life on the Indian stage.",
  },
  {
    eventName: "Macbeth – A Modern Adaptation",
    eventDate: new Date("2025-12-10"),
    pricePerTicket: 900,
    ticketsAvailable: 80,
    owner: "68ff509c77bb306c3224e66e",
    location: "Kamani Auditorium, Delhi",
    eventCategory: "Theatre",
    description: "A gripping modern retelling of Shakespeare’s tragic masterpiece.",
  },

  // 🎡 Festivals
  {
    eventName: "Sunburn Goa 2025",
    eventDate: new Date("2025-12-29"),
    pricePerTicket: 5500,
    ticketsAvailable: 1000,
    owner: "68ff509c77bb306c3224e66e",
    location: "Vagator Beach, Goa",
    eventCategory: "Festival",
    description: "Asia’s biggest EDM festival with global artists and beach vibes.",
  },
  {
    eventName: "Jaipur Literature Festival 2025",
    eventDate: new Date("2025-01-24"),
    pricePerTicket: 400,
    ticketsAvailable: 800,
    owner: "68ff509c77bb306c3224e66e",
    location: "Diggi Palace, Jaipur",
    eventCategory: "Festival",
    description: "Celebrate books, authors, and conversations at the world’s biggest lit fest.",
  },

  // 😂 Comedy
  {
    eventName: "Zakir Khan – Live Tour",
    eventDate: new Date("2025-11-22"),
    pricePerTicket: 1500,
    ticketsAvailable: 200,
    owner: "68ff509c77bb306c3224e66e",
    location: "Siri Fort Auditorium, Delhi",
    eventCategory: "Comedy",
    description: "Catch Zakir Khan’s signature humor and storytelling live on stage.",
  },
  {
    eventName: "Kenny Sebastian – Professor of Tomfoolery",
    eventDate: new Date("2025-12-05"),
    pricePerTicket: 1300,
    ticketsAvailable: 180,
    owner: "68ff509c77bb306c3224e66e",
    location: "Good Shepherd Auditorium, Bengaluru",
    eventCategory: "Comedy",
    description: "A hilarious evening with Kenny Sebastian and his new stand-up special.",
  },

  // 🎤 Other Events
  {
    eventName: "TechCrunch India Summit",
    eventDate: new Date("2025-12-08"),
    pricePerTicket: 2000,
    ticketsAvailable: 300,
    owner: "68ff509c77bb306c3224e66e",
    location: "Hyderabad Convention Centre, Hyderabad",
    eventCategory: "Other",
    description: "India’s leading tech startup conference with global investors and founders.",
  },
  {
    eventName: "Food Fiesta – Delhi Street Food Carnival",
    eventDate: new Date("2025-11-18"),
    pricePerTicket: 500,
    ticketsAvailable: 600,
    owner: "68ff509c77bb306c3224e66e",
    location: "India Gate Lawns, Delhi",
    eventCategory: "Other",
    description: "Taste the best of Indian street food at one grand event.",
  },

  // Additional 8 randoms
  {
    eventName: "Prateek Kuhad – Winter Tour",
    eventDate: new Date("2025-12-21"),
    pricePerTicket: 2100,
    ticketsAvailable: 150,
    owner: "68ff509c77bb306c3224e66e",
    location: "Phoenix Marketcity, Pune",
    eventCategory: "Concert",
    description: "Feel the warmth of Prateek Kuhad’s melodies this winter.",
  },
  {
    eventName: "India vs Pakistan – T20 Match",
    eventDate: new Date("2025-12-25"),
    pricePerTicket: 3000,
    ticketsAvailable: 700,
    owner: "68ff509c77bb306c3224e66e",
    location: "Wankhede Stadium, Mumbai",
    eventCategory: "Sports",
    description: "Witness the greatest cricket rivalry in the world!",
  },
  {
    eventName: "Lollapalooza India 2025",
    eventDate: new Date("2025-12-18"),
    pricePerTicket: 4900,
    ticketsAvailable: 950,
    owner: "68ff509c77bb306c3224e66e",
    location: "Mahalaxmi Race Course, Mumbai",
    eventCategory: "Festival",
    description: "Global artists and indie bands unite for two days of epic music.",
  },
  {
    eventName: "Trevor Noah – Off the Record",
    eventDate: new Date("2025-12-01"),
    pricePerTicket: 2800,
    ticketsAvailable: 220,
    owner: "68ff509c77bb306c3224e66e",
    location: "Siri Fort Auditorium, Delhi",
    eventCategory: "Comedy",
    description: "Trevor Noah returns to India for his world comedy tour.",
  },
  {
    eventName: "The Great Indian Circus",
    eventDate: new Date("2025-11-17"),
    pricePerTicket: 700,
    ticketsAvailable: 400,
    owner: "68ff509c77bb306c3224e66e",
    location: "Chennai Trade Centre, Chennai",
    eventCategory: "Other",
    description: "A spectacular family-friendly circus filled with stunts and laughter.",
  },
  {
    eventName: "Stand-Up for a Cause – Charity Night",
    eventDate: new Date("2025-11-30"),
    pricePerTicket: 800,
    ticketsAvailable: 250,
    owner: "68ff509c77bb306c3224e66e",
    location: "Kala Academy, Goa",
    eventCategory: "Comedy",
    description: "Top comedians come together for a special fundraising night.",
  },
  {
    eventName: "Rajasthan Folk Festival",
    eventDate: new Date("2025-10-30"),
    pricePerTicket: 1000,
    ticketsAvailable: 400,
    owner: "68ff509c77bb306c3224e66e",
    location: "Mehrangarh Fort, Jodhpur",
    eventCategory: "Festival",
    description: "Immerse yourself in the vibrant folk music and art of Rajasthan.",
  },
  {
    eventName: "WWE India Live 2025",
    eventDate: new Date("2025-12-12"),
    pricePerTicket: 3500,
    ticketsAvailable: 900,
    owner: "68ff509c77bb306c3224e66e",
    location: "Indira Gandhi Indoor Stadium, Delhi",
    eventCategory: "Sports",
    description: "WWE superstars bring their power-packed action to India!",
  },
];

module.exports = tickets;
